import React from "react";
import Particles from "react-tsparticles";

function Particle() {
  return (
    <Particles
      id="tsparticles"
      params={{
        "particles":{
          "number":{
             "value":40,
             "density":{
                "enable":true,
                "value_area":1736.124811591
             }
          },
          "color":{
             "value":"#D0FFCE"
          },
          "shape":{
             "type":"square",
             "stroke":{
                "width":8,
                "color":"#000000"
             },
             "polygon":{
                "nb_sides":4
             },
             "image":{
                "src":"img/github.svg",
                "width":100,
                "height":100
             }
          },
          "opacity":{
             "value":0.6,
             "random":false,
             "anim":{
                "enable":false,
                "speed":1,
                "opacity_min":0.1,
                "sync":false
             }
          },
          "size":{
             "value":7.891476416322726,
             "random":true,
             "anim":{
                "enable":false,
                "speed":40,
                "size_min":0.1,
                "sync":false
             }
          },
          "line_linked":{
             "enable":true,
             "distance":0,
             "color":"#ffffff",
             "opacity":0.2919846274039409,
             "width":2.8409315098761816
          },
          "move":{
             "enable":true,
             "speed":1.5782952832645452,
             "direction":"random",
             "random":false,
             "straight":false,
             "out_mode":"bounce",
             "bounce":false,
             "attract":{
                "enable":true,
                "rotateX":600,
                "rotateY":1200
             }
          }
       },
       "interactivity":{
        "detect_on":"canvas",
        "events":{
           "onhover":{
              "enable":true,
              "mode":"bubble"
           },
           "onclick":{
              "enable":false,
              "mode":"push"
           },
           "resize":true
        },
        "modes":{
           "grab":{
              "distance":400,
              "line_linked":{
                 "opacity":1
              }
           },
           "bubble":{
              "distance":400,
              "size":40,
              "duration":2,
              "opacity":8,
              "speed":3
           },
           "repulse":{
              "distance":200,
              "duration":0.4
           },
           "push":{
              "particles_nb":4
           },
           "remove":{
              "particles_nb":2
           }
        }
     },
        retina_detect: true,
      }}
    />
  );
}

export default Particle;
